#! /bin/bash
# /etc/init.d/ShopCam

### BEGIN INIT INFO
# Provides:          ShopCam
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Simple script to start a program at boot
# Description:       A simple script from www.stuffaboutcode.com which will start / stop a program a boot / shutdown.
### END INIT INFO

# If you want a command to always run, put it here

# Carry out specific functions when asked to by the system
# Operate the service with:
# sudo /etc/init.d/ShopCam start
# sudo /etc/init.d/ShopCam stop

RTMP_URL=rtmp://URL
STREAM_KEY=KEY

case "$1" in
  start)
    echo "Starting ShopCam"
    # Ustream
    # BenHeckShopCam
    `raspivid -t 9999999 -w 320 -h 240 -fps 25 -b 500000 -o - | avconv -i - -pix_fmt yuv420p -metadata title="Streaming from raspberry pi camera" -f flv $RTMP_URL/$STREAM_KEY` 
    ;;
  stop)
    echo "Stopping ShopCam"
    # kill application you want to stop
    killall raspivid
    killall avconv
    ;;
  *)
    echo "Usage: /etc/init.d/ShopCam {start|stop}"
    exit 1
    ;;
esac

exit 0
